from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=200)

class Text(models.Model):
    author = models.ForeignKey('Author')

    name = models.CharField(max_length=200)
    text_file = models.FileField(default=None, null=True, blank=True)

class Chunk(models.Model):
    author = models.ForeignKey('Author')

    text = models.ForeignKey('Text')
    text_chunk_number = models.IntegerField(null=True)
    chunk_file = models.FileField(default=None, null=True, blank=True)

    # fingerprint
    # todo: Find a better way to store all this nonsense
    avg_word_length     = models.FloatField(null=True)
    avg_sentence_length = models.FloatField(null=True)
    lexical_diversity   = models.FloatField(null=True)
    percentage_punctuation  = models.FloatField(null=True)
    # function words
    the_relative_frequency     = models.FloatField(null=True)
    and_relative_frequency     = models.FloatField(null=True)
    of_relative_frequency      = models.FloatField(null=True)
    a_relative_frequency       = models.FloatField(null=True)
    to_relative_frequency      = models.FloatField(null=True)
    in_relative_frequency      = models.FloatField(null=True)
    i_relative_frequency       = models.FloatField(null=True)
    he_relative_frequency      = models.FloatField(null=True)
    it_relative_frequency      = models.FloatField(null=True)
    that_relative_frequency    = models.FloatField(null=True)
    you_relative_frequency     = models.FloatField(null=True)
    his_relative_frequency     = models.FloatField(null=True)
    with_relative_frequency    = models.FloatField(null=True)
    on_relative_frequency      = models.FloatField(null=True)
    for_relative_frequency     = models.FloatField(null=True)
    at_relative_frequency      = models.FloatField(null=True)
    as_relative_frequency      = models.FloatField(null=True)
    but_relative_frequency     = models.FloatField(null=True)
    her_relative_frequency     = models.FloatField(null=True)
    they_relative_frequency    = models.FloatField(null=True)
    she_relative_frequency     = models.FloatField(null=True)
    him_relative_frequency     = models.FloatField(null=True)
    all_relative_frequency     = models.FloatField(null=True)
    this_relative_frequency    = models.FloatField(null=True)
    we_relative_frequency      = models.FloatField(null=True)
    from_relative_frequency    = models.FloatField(null=True)
    or_relative_frequency      = models.FloatField(null=True)
    out_relative_frequency     = models.FloatField(null=True)
    an_relative_frequency      = models.FloatField(null=True)
    my_relative_frequency      = models.FloatField(null=True)
    by_relative_frequency      = models.FloatField(null=True)
    up_relative_frequency      = models.FloatField(null=True)
    what_relative_frequency    = models.FloatField(null=True)
    me_relative_frequency      = models.FloatField(null=True)
    no_relative_frequency      = models.FloatField(null=True)
    like_relative_frequency    = models.FloatField(null=True)
    would_relative_frequency   = models.FloatField(null=True)
    if_relative_frequency      = models.FloatField(null=True)
    about_relative_frequency   = models.FloatField(null=True)
    which_relative_frequency   = models.FloatField(null=True)
    them_relative_frequency    = models.FloatField(null=True)
    into_relative_frequency    = models.FloatField(null=True)
    who_relative_frequency     = models.FloatField(null=True)
    could_relative_frequency   = models.FloatField(null=True)
    can_relative_frequency     = models.FloatField(null=True)
    some_relative_frequency    = models.FloatField(null=True)
    their_relative_frequency   = models.FloatField(null=True)
    over_relative_frequency    = models.FloatField(null=True)
    down_relative_frequency    = models.FloatField(null=True)
    your_relative_frequency    = models.FloatField(null=True)
    will_relative_frequency    = models.FloatField(null=True)
    its_relative_frequency     = models.FloatField(null=True)
    any_relative_frequency     = models.FloatField(null=True)
    through_relative_frequency = models.FloatField(null=True)
    after_relative_frequency   = models.FloatField(null=True)
    off_relative_frequency     = models.FloatField(null=True)
    than_relative_frequency    = models.FloatField(null=True)
    our_relative_frequency     = models.FloatField(null=True)
    us_relative_frequency      = models.FloatField(null=True)
    around_relative_frequency  = models.FloatField(null=True)
    these_relative_frequency   = models.FloatField(null=True)
    because_relative_frequency = models.FloatField(null=True)
    must_relative_frequency    = models.FloatField(null=True)
    before_relative_frequency  = models.FloatField(null=True)
    those_relative_frequency   = models.FloatField(null=True)
    ampersand_relative_frequency = models.FloatField(null=True)
    should_relative_frequency  = models.FloatField(null=True)
    himself_relative_frequency = models.FloatField(null=True)
    both_relative_frequency    = models.FloatField(null=True)
    against_relative_frequency = models.FloatField(null=True)
    may_relative_frequency     = models.FloatField(null=True)
    might_relative_frequency   = models.FloatField(null=True)
    shall_relative_frequency   = models.FloatField(null=True)
    since_relative_frequency   = models.FloatField(null=True)
    de_relative_frequency      = models.FloatField(null=True)
    within_relative_frequency  = models.FloatField(null=True)
    between_relative_frequency = models.FloatField(null=True)
    each_relative_frequency    = models.FloatField(null=True)
    under_relative_frequency   = models.FloatField(null=True)
    until_relative_frequency   = models.FloatField(null=True)
    toward_relative_frequency  = models.FloatField(null=True)
    another_relative_frequency = models.FloatField(null=True)
    myself_relative_frequency  = models.FloatField(null=True)
    PRP_pos_relative_frequency     = models.FloatField(null=True)
    VBG_pos_relative_frequency     = models.FloatField(null=True)
    VBD_pos_relative_frequency     = models.FloatField(null=True)
    VBN_pos_relative_frequency     = models.FloatField(null=True)
    POS_pos_relative_frequency     = models.FloatField(null=True)
    VBP_pos_relative_frequency     = models.FloatField(null=True)
    WDT_pos_relative_frequency     = models.FloatField(null=True)
    JJ_pos_relative_frequency      = models.FloatField(null=True)
    WP_pos_relative_frequency      = models.FloatField(null=True)
    VBZ_pos_relative_frequency     = models.FloatField(null=True)
    DT_pos_relative_frequency      = models.FloatField(null=True)
    RP_pos_relative_frequency      = models.FloatField(null=True)
    NN_pos_relative_frequency      = models.FloatField(null=True)
    FW_pos_relative_frequency      = models.FloatField(null=True)
    TO_pos_relative_frequency      = models.FloatField(null=True)
    PRP_pos_relative_frequency     = models.FloatField(null=True)
    RB_pos_relative_frequency      = models.FloatField(null=True)
    NNS_pos_relative_frequency     = models.FloatField(null=True)
    NNP_pos_relative_frequency     = models.FloatField(null=True)
    VB_pos_relative_frequency      = models.FloatField(null=True)
    WRB_pos_relative_frequency     = models.FloatField(null=True)
    CC_pos_relative_frequency      = models.FloatField(null=True)
    LS_pos_relative_frequency      = models.FloatField(null=True)
    PDT_pos_relative_frequency     = models.FloatField(null=True)
    RBS_pos_relative_frequency     = models.FloatField(null=True)
    RBR_pos_relative_frequency     = models.FloatField(null=True)
    CD_pos_relative_frequency      = models.FloatField(null=True)
    EX_pos_relative_frequency      = models.FloatField(null=True)
    IN_pos_relative_frequency      = models.FloatField(null=True)
    WP_pos_relative_frequency     = models.FloatField(null=True)
    MD_pos_relative_frequency      = models.FloatField(null=True)
    NNPS_pos_relative_frequency    = models.FloatField(null=True)
    JJS_pos_relative_frequency     = models.FloatField(null=True)
    JJR_pos_relative_frequency     = models.FloatField(null=True)
    UH_pos_relative_frequency      = models.FloatField(null=True)
